#!/usr/bin/env bash

set -euo pipefail

if ! command -v gawk >/dev/null 2>&1; then
  echo "ERROR: gawk required (apt install gawk; brew install gawk)" >&2
  exit 1
fi

VERUS_ROOT="${VERUS_ROOT:-.}"
cd "$VERUS_ROOT"

OUT="OBLIGATIONS.md"
SRC_DIR="src"
MODULES=(lib pool concurrent)

missing=0
for m in "${MODULES[@]}"; do
  [[ -f "$SRC_DIR/$m.rs" ]] || { echo "MISSING: $SRC_DIR/$m.rs" >&2; missing=1; }
  [[ -f "verus-$m.log" ]]   || { echo "MISSING: verus-$m.log (run reproduce.sh first)" >&2; missing=1; }
done
[[ $missing -eq 0 ]] || exit 1

declare -A COUNT
for m in "${MODULES[@]}"; do
  COUNT[$m]=$(grep -oE "[0-9]+ verified" "verus-$m.log" \
              | grep -oE "^[0-9]+" | head -1 || echo 0)
done
TOTAL=$(( COUNT[lib] + COUNT[pool] + COUNT[concurrent] ))

extract_obligations() {
  local file="$1"

  gawk '
    BEGIN {
      in_sig = 0
      fn_name = ""
      fn_kind = ""
      has_req = 0
      has_ens = 0
      has_rec = 0
    }
    /(^|[[:space:]])fn[[:space:]]+[a-zA-Z_][a-zA-Z0-9_]*/ && !in_sig {
      line = $0

      # Detect kind from any preceding modifiers on same line.
      kind = "fn"
      if (match(line, /(spec|proof|exec)[[:space:]]+fn/, k)) {
        kind = k[1] " fn"
      }

      # Extract function name.
      if (match(line, /fn[[:space:]]+([a-zA-Z_][a-zA-Z0-9_]*)/, m)) {
        fn_name = m[1]
        fn_kind = kind
        in_sig = 1
        has_req = 0; has_ens = 0; has_rec = 0
      }
    }
    in_sig && /(^|[^a-zA-Z0-9_])requires([^a-zA-Z0-9_]|$)/   { has_req = 1 }
    in_sig && /(^|[^a-zA-Z0-9_])ensures([^a-zA-Z0-9_]|$)/    { has_ens = 1 }
    in_sig && /(^|[^a-zA-Z0-9_])recommends([^a-zA-Z0-9_]|$)/ { has_rec = 1 }
    # End of signature: any opening brace, provided we are in a sig.
    # (Matches both multi-line `{ \n body \n }` and one-liner `{}` bodies.
    # Excludes `= {` which would be an assignment to a block expression.)
    in_sig && /\{/ && !/=[[:space:]]*\{/ {
      if (has_req || has_ens) {
        flags = ""
        if (has_req) flags = flags " requires"
        if (has_ens) flags = flags " ensures"
        if (has_rec) flags = flags " recommends"
        printf("| `%s` | %s |%s |\n", fn_name, fn_kind, flags)
      }
      in_sig = 0; fn_name = ""; has_req = 0; has_ens = 0; has_rec = 0
    }
  ' "$file"
}

cat > "$OUT" <<EOF
# Verus Obligations — Token Budgets

Auto-generated by \`gen_obligations.sh\` on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
from \`src/{lib,pool,concurrent}.rs\` and the per-module Verus logs.

## Counts (verified)

| Module               | Obligations |
|----------------------|-------------|
| \`src/lib.rs\`         | ${COUNT[lib]}            |
| \`src/pool.rs\`        | ${COUNT[pool]}            |
| \`src/concurrent.rs\`  | ${COUNT[concurrent]}            |
| **Total**            | **${TOTAL}**           |

Counts taken directly from \`verus-{lib,pool,concurrent}.log\`. Paper
claim is **66 obligations across three modules** (\S\ref{sec:not-verified}); the
\`reproduce.sh\` harness fails if this script's TOTAL is not 66.

## Reproduction

\`\`\`bash
# From repository root:
cd token-budgets-formals/verus
verus src/lib.rs       2>&1 | tee verus-lib.log
verus src/pool.rs      2>&1 | tee verus-pool.log
verus src/concurrent.rs 2>&1 | tee verus-concurrent.log
bash gen_obligations.sh   # regenerates this file
\`\`\`

Or, as a single step from the paper's reproduction harness:

\`\`\`bash
bash reproduce.sh   # Verus step writes the three logs; gen runs after
\`\`\`

## Index of obligation-bearing functions

The index below lists every function in the three modules carrying
at least one \`requires\` or \`ensures\` clause — the artefact-level
counterpart of "66 obligations". Note that Verus may discharge
multiple proof obligations per function (one per clause, plus
internal verification conditions), so the function count is a lower
bound on the obligation count by construction; the authoritative
total is the per-module log sum reported above.

For the exact predicates (the contents of each \`requires\`/\`ensures\`
clause), read the source files referenced below.

EOF

for m in "${MODULES[@]}"; do
  cat >> "$OUT" <<EOF

### \`src/$m.rs\` (${COUNT[$m]} obligations per \`verus-$m.log\`)

| Function | Kind | Clauses |
|----------|------|---------|
EOF
  extract_obligations "$SRC_DIR/$m.rs" >> "$OUT" || true
done

cat >> "$OUT" <<EOF

## Trust assumptions

This per-module decomposition is contingent on Verus's standard
trust assumptions, documented in VerusBelt (Hance, Elbeheiry,
Matsushita, and Dreyer, PLDI 2026): ghost erasure, translation to
Z3, and a simplified type-layout model. Our Tier-4 verification
result inherits these assumptions. See the paper's
"What is not formally verified" section for the full list of
not-verified items.
EOF

echo "Wrote $OUT (total: $TOTAL obligations)"
if [[ "$TOTAL" -ne 66 ]]; then
  echo "WARNING: total $TOTAL != 66 (paper claim). Update paper or check Verus output." >&2
  exit 2
fi
exit 0